import Anthropic from "@anthropic-ai/sdk";
import fs from "fs";
import path from "path";
import { WorkflowGraphSchema, type WorkflowGraph } from "@flowops/schemas";
import { z } from "zod";

const LlmOutputSchema = z.object({
  name: z.string().min(1).catch("AI Generated Workflow"),
  description: z.string().catch("Generated by AI"),
  nodes: z.array(z.any()),
  edges: z.array(z.any()).optional(),
});
import db from "../db";

const MAX_RETRIES = 3;

// Load prompt templates from /prompts at the repo root
const PROMPTS_DIR = path.resolve(__dirname, "../../../../prompts");

function loadPrompt(filename: string): string {
  return fs.readFileSync(path.join(PROMPTS_DIR, filename), "utf-8");
}

// ─── LLM Client ─────────────────────────────────────────────────
// Abstracted so tests can inject a mock

export interface LlmClient {
  generateText(systemPrompt: string, userMessage: string): Promise<string>;
}

export class AnthropicLlmClient implements LlmClient {
  private client: Anthropic;

  constructor(apiKey?: string) {
    this.client = new Anthropic({
      apiKey: apiKey || process.env.ANTHROPIC_API_KEY,
    });
  }

  async generateText(systemPrompt: string, userMessage: string): Promise<string> {
    const response = await this.client.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 4096,
      system: systemPrompt,
      messages: [{ role: "user", content: userMessage }],
    });

    // Extract text from the response
    const textBlock = response.content.find((block) => block.type === "text");
    if (!textBlock || textBlock.type !== "text") {
      throw new Error("LLM returned no text content");
    }
    return textBlock.text;
  }
}

// ─── Validation Result ──────────────────────────────────────────

export interface GenerationResult {
  success: boolean;
  workflow?: { name: string; description: string } & WorkflowGraph;
  error?: string;
  attempts: number;
}

// ─── Workflow Generator ─────────────────────────────────────────

export class WorkflowGenerator {
  private llm: LlmClient;
  private systemPrompt: string;
  private retryPromptTemplate: string;

  constructor(llm?: LlmClient) {
    this.llm = llm || new AnthropicLlmClient();
    this.systemPrompt = loadPrompt("workflow-generation.md");
    this.retryPromptTemplate = loadPrompt("workflow-generator-retry.md");
  }

  async generate(userRequirement: string, workflowId?: string): Promise<GenerationResult> {
    let lastRawOutput = "";
    let lastErrors = "";

    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      try {
        let userMessage: string;

        if (attempt === 0) {
          // First attempt: send the raw user requirement
          userMessage = userRequirement;
        } else {
          // Retry: send the specific validation errors
          userMessage = this.retryPromptTemplate.replace(
            "{{VALIDATION_ERRORS}}",
            lastErrors
          );
        }

        const rawOutput = await this.llm.generateText(this.systemPrompt, userMessage);
        lastRawOutput = rawOutput;

        // Try to parse JSON from the response (strip markdown fences if present)
        const jsonStr = this.extractJson(rawOutput);
        const parsed = JSON.parse(jsonStr);

        // Validate the wrapper structure
        const wrapperResult = LlmOutputSchema.safeParse(parsed);
        if (!wrapperResult.success) {
           throw new Error("Missing required wrapper fields (name, description, nodes, edges)");
        }

        // Validate the graph
        const result = WorkflowGraphSchema.safeParse({
           nodes: wrapperResult.data.nodes,
           edges: wrapperResult.data.edges ?? []
        });

        // Log this attempt
        await this.logAttempt(workflowId, userRequirement, rawOutput, result.success, 
          result.success ? undefined : JSON.stringify(result.error.issues), attempt);

        if (result.success) {
          return {
            success: true,
            workflow: {
               name: wrapperResult.data.name,
               description: wrapperResult.data.description,
               nodes: result.data.nodes,
               edges: result.data.edges
            },
            attempts: attempt + 1,
          };
        }

        // Format errors for the retry prompt
        lastErrors = result.error.issues
          .map((issue) => `- ${issue.path.join(".")}: ${issue.message}`)
          .join("\n");

      } catch (err: any) {
        const errorMsg = err instanceof SyntaxError
          ? `JSON parse error: ${err.message}`
          : err.message;

        lastErrors = errorMsg;

        // Log the failed attempt
        await this.logAttempt(workflowId, userRequirement, lastRawOutput, false, errorMsg, attempt);
      }
    }

    // All retries exhausted
    return {
      success: false,
      error: `Failed to generate a valid workflow after ${MAX_RETRIES + 1} attempts. Last errors:\n${lastErrors}`,
      attempts: MAX_RETRIES + 1,
    };
  }

  /**
   * Strip markdown code fences and extract the JSON object
   */
  private extractJson(raw: string): string {
    // Remove ```json ... ``` or ``` ... ``` wrappers
    const fenceMatch = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (fenceMatch) {
      return fenceMatch[1].trim();
    }
    // Otherwise assume the whole thing is JSON
    return raw.trim();
  }

  /**
   * Log every generation attempt to the database for metrics
   */
  private async logAttempt(
    workflowId: string | undefined,
    userPrompt: string,
    rawOutput: string,
    isValid: boolean,
    validationErrors: string | undefined,
    retryNumber: number
  ): Promise<void> {
    try {
      await db.llmGenerationLog.create({
        data: {
          workflowId: workflowId || null,
          userPrompt,
          rawLlmOutput: rawOutput,
          isValid,
          validationErrors: validationErrors || null,
          retryNumber,
        },
      });
    } catch (logErr) {
      // Don't let logging failures break the generation flow
      console.error("Failed to log LLM attempt:", logErr);
    }
  }
}
